### PR TITLE
Poles and zeros for SISO systems

### PR DESCRIPTION
**Pull request by CristianRojas**
### Changes

Short summary of the changes:
- Added one-liners for the "zeros" and "poles" functions for SISO systems
- Also added "issiso" and "ismimo" functions

### CODE REVIEW

**Comment by CristianRojas** [comment]
@aytekinar: In statespace.jl, several functions (likes `zeros` and `poles`) depend on expressions of the form `eigfact(Am).values::Vector{Complex{Float64}}`, which seem to fail if Am has only real eigenvalues.

As an example of this, you can run

`eigfact([0.1 0; 0 0.3]).values::Vector{Complex{Float64}}`

which gives the error

`ERROR: TypeError: typeassert: expected Array{Complex{Float64},1}, got Array{Float64,1}`

Any suggestions? :)

**Comment by aytekinar** [comment]
Wow.. Great comment! Thanks!

Then, instead of the assertion, we can make sure we have conversion:

```julia
convert(Vector{Complex128}, eigfact(Am).values)
```

Or, we just do not care about it. Here, I will ask your suggestions.

The reason for the assertion was to ensure type-stability when returning from functions. However,

```julia
@code_warntype eigfact([0.1 0; 0 0.3])
```

is itself type unstable.

How would you like to proceed? Ensuring that we always return complex numbers for roots, or let Julia return properly?

Cc: @neveritt

**Comment by CristianRojas** [comment]
Thank you for your reply, @aytekinar!

I don't know which would be the best solution. As you mention, without conversion these functions would be type unstable. However, in many occasions, when using the poles or zeros of a system in another function (for example, within ControlToolbox.jl), we have to consider real and complex poles separately, so even if we convert them to a complex type, we would need to check afterwards if the imaginary parts are zero or not. In this sense, it wouldn't be so bad to avoid the conversion and return directly the output of eigfact. What do you think?

Cc: @neveritt

**Comment by CristianRojas** [comment]
@aytekinar: Another issue: in `methods/rosenbrock.jl`, we should replace `sub` by `view`.

Cc: @neveritt

**Comment by aytekinar** [comment]
In terms of type-stability, @CristianRojas, I am not sure we should go for Option 1, as it would be harder to maintain. I mean, if, in the future, the language committee decides to do something different, we need to keep an eye on their changes consistently.

Then, your Option 2 is valid and reasonable --- either we will forget about type stability, and move on with whatever Julia provides us with --- in the end, we are not responsible for introducing type instability. Or, we just convert to `Vector{Complex128}` whatever we receive. Since `convert{T}(::Type{T}, t::T) = t`, it is a no-op. If not, we will receive the complex values. Then, if we need some specialization on real poles/zeros, we can use a check similar to `imag(pole) == zero(pole)`.

I think, from this point on, it is a matter of taste and a design choice. I do not see any big concern in any of the branch we take in Option 2.

Cc: @neveritt.

**Pull request closed without merging**
